service: coronavirus-historical-data
app: coronavirus-info
org: spenceraung

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-northeast-1

functions:
  hello:
    handler: handler.hello
    # events:
      # Invoke Lambda function every minute
      # - schedule: rate(1 minute)
  save:
    handler: handler.save
